#!/bin/bash

set -e

# Only fudge the architecture for non-x86-64 systems.
[ "$(uname -m)" == "x86-64" ] && exit 0

for dir in *_linux26-x86-64; do
mv $dir ${dir%-x86-64}-$(uname -m)
done

sed -i "s/_linux26-x86-64/_linux26-$(uname -m)/g" Makefile

make /home/ssm/GIT_CACHE/ssmuse_fork.git VGRID_RELEASE=none
pushd /home/ssm/GIT_CACHE/ssmuse_fork.git
# Add arm detection to ssmuse_platforms.
git apply /tmp/ssmuse_platforms.sh.patch
# Add arm architectures to the database.
echo "debian-8.0-armv6l-32 raspbian-8.0-armv6l-32 linux26-armv6l:" > etc/ssmuse/platforms/debian/debian-8.0-armv6l-32
echo "debian-8.0-armv7l-32 raspbian-8.0-armv7l-32 linux26-armv7l:" > etc/ssmuse/platforms/debian/debian-8.0-armv7l-32
# Commit these changes so they get picked up by rmnlib-install.
git add .
git config --global --add user.name "ssm"
git config --global --add user.email "ssm@localhost"
git commit --message="Add more architectures."
popd
# Define compiler rules and macros for arm
make /home/ssm/GIT_CACHE/code-tools VGRID_RELEASE=none
pushd /home/ssm/GIT_CACHE/code-tools
mkdir -p include/Linux_armv6l/gfortran
cp include/Linux_x86-64/gfortran/rpn_macros_arch.h include/Linux_armv6l/gfortran/
sed 's/-DAmd64=Amd64//;/[FC]C_options/s/ -m[^ ]*//g;' include/Linux_x86-64/gfortran/Compiler_rules > include/Linux_armv6l/gfortran/Compiler_rules
pushd include/
ln -s Linux_armv6l Linux_armv7l
popd
git add .
git commit --message="Add arm rules."
popd


# Handle arm architectures.
arch=$(uname -m)
# Disable inline assembly call for perftools.
if [ "$arch" == "armv6l" -o "$arch" == "armv7l" ]; then
sed -i 's/use_rdtsc=1/use_rdtsc=0/;/^ *asm/d' perf-tools_1.1_linux26-armv6l/src/JIO/jio-uni-2.c
sed -i 's/-m32//;/linux-64/d' perf-tools_1.1_linux26-armv6l/src/JIO/Makefile
fi
# Copy alternative timing routine from pertools to rpncomm.
# Avoids using x86 inline assembly.
# Also, freeze the rpncomm source on a known good commit.
# Some later commit (Jan 2019) seems to be causing a build failure?
sed -i 's:^git checkout.*:git checkout a0008d0e9f56a0c7f47581ab7a7e0454e26529f1\ngit apply /tmp/RPN_COMM_wtime.c.patch:' rpncomm_4.5.16_linux26-$(uname -m)/.ssm.d/post-install
